name: "Dependabot"

on:
  schedule:
    - cron: '0 7 * * *' # Runs at 2am Central every morning
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run dependabot
      uses: dependabot/dependabot-script@v1
      with:
        script: |
          dependabot update --package-ecosystem=javascript
