name: "Secret Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run secret scanning
      uses: github/codeql-action/analyze@v2
      with:
        languages: "all"
        query: "security-extended.ql"
        fail-on-errors: true
